name: Security Scanning

on:
  push:
    branches: [ main, develop ]
  schedule:
    - cron: '0 0 * * 0' # Weekly scans

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Scan dependencies
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-fs.sarif'

  container-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build container
      run: docker build -t ragagument:scan .
    - name: Scan container
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ragagument:scan'
        format: 'sarif'
        output: 'trivy-container.sarif'
        severity: 'CRITICAL,HIGH'

  code-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        languages: python

  secret-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      with:
        config-path: .gitleaks.toml
        redact: true

  sbom-generation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate SBOM
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ragagument:scan'
        format: 'spdx-json'
        output: 'sbom.json'
        command: 'sbom'
    - name: Upload SBOM
      uses: actions/upload-artifact@v3
      with:
        name: sbom
        path: sbom.json